version: "3.9"
services:
  app:
    build: .
    container_name: nest-socket
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-nest-socket
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - .env
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
  redis:
    image: redis:7.0
    container_name: redis-nest-socket
    restart: always
    ports:
      - "6380:6379"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}" # password lấy từ .env
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-nest-socket
    restart: always
    ports:
      - "${RABBITMQ_AMQP_PORT:-5672}:${RABBITMQ_AMQP_PORT:-5672}" # port cho app kết nối
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:${RABBITMQ_MANAGEMENT_PORT:-15672}" # port quản lý web
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER:-guest}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD:-guest}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  mongo_data:
    driver: local
